import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "FFN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link 
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;700&display=swap" 
        rel="stylesheet"
        />

      </head> */}
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
